title: PugSQL
email: mcfunley@gmail.com
twitter_username: mcfunley
github_username: mcfunley

markdown: kramdown
plugins:
  - jekyll-gist
  - jekyll-sitemap

exclude:
  - _pdoc

sass:
  sass_dir: _scss
